{% set name = "fiona" %}
{% set version = "1.10.0" %}

package:
  name: fiona
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fiona-{{ version }}.tar.gz
  sha256: 3529fd46d269ff3f70aeb9316a93ae95cf2f87d7e148a8ff0d68532bf81ff7ae
  patches:
    - 0001-remove-certifi-dependency.patch

build:
  number: 0
  script_env:
    - GDAL_ENABLE_DEPRECATED_DRIVER_GTM=YES
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [unix]
  entry_points:
    - fio = fiona.fio.main:main_group

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.2,<3.1.dev0
    - setuptools >=67.8
    - libgdal
  run:
    - certifi
    - python
    - gdal
    - attrs >=19.2.0
    - click >=8.0,<9.dev0
    - cligj >=0.5
    - click-plugins >=1.0
    - importlib-metadata  # [py<310]
    - shapely  # only option calc we include by default

test:
  source_files:
    - tests
  imports:
    - fiona
    - fiona.fio
  requires:
    - pytest >=3
    - boto3 >=1.2.4
    - packaging
    - pip
    - pytz
  files:
    - test_data
  commands:
    - pip check
    - fio --help
    - fio ls test_data/test.shp
    - fio info test_data/test.shp

about:
  home: http://github.com/Toblerity/Fiona
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Fiona reads and writes spatial data files

extra:
  recipe-maintainers:
    - zklaus
    - akrherz
    - ocefpaf
    - jorisvandenbossche
    - xylar
